"""Rename total_articles to last_article_count

Revision ID: 161ecb4ddd29
Revises: acf26aaa2f75
Create Date: 2026-01-06 12:25:25.073264

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "161ecb4ddd29"
down_revision: Union[str, Sequence[str], None] = "acf26aaa2f75"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Add new column with default, copy data, then drop old column
    with op.batch_alter_table("source_stats_daily", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("last_article_count", sa.Integer(), nullable=False, server_default="0")
        )

    # Copy data from old column to new
    op.execute("UPDATE source_stats_daily SET last_article_count = total_articles")

    with op.batch_alter_table("source_stats_daily", schema=None) as batch_op:
        batch_op.drop_column("total_articles")


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("source_stats_daily", schema=None) as batch_op:
        batch_op.add_column(sa.Column("total_articles", sa.INTEGER(), nullable=False))
        batch_op.drop_column("last_article_count")

    # ### end Alembic commands ###
