"""Add users table and user_id to newsletters

Revision ID: 1bfd219c01d9
Revises: 2bbcede10542
Create Date: 2025-12-11 19:21:12.434033

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "1bfd219c01d9"
down_revision: Union[str, Sequence[str], None] = "2bbcede10542"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Create users table first (newsletters will reference it)
    op.create_table(
        "users",
        # Core fields
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(length=100), nullable=True),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("preferred_categories", sa.Text(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("last_login_at", sa.DateTime(timezone=True), nullable=True),
        # Auth fields
        sa.Column("password_hash", sa.String(length=255), nullable=True),
        sa.Column("google_id", sa.String(length=255), nullable=True),
        # Settings
        sa.Column("email_notifications", sa.Boolean(), nullable=False),
        # Timestamps
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("google_id"),
    )
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_users_email"), ["email"], unique=True)

    # Add user_id column to newsletters table
    with op.batch_alter_table("newsletters", schema=None) as batch_op:
        batch_op.add_column(sa.Column("user_id", sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f("ix_newsletters_user_id"), ["user_id"], unique=False)
        batch_op.create_foreign_key(
            "fk_newsletters_user_id", "users", ["user_id"], ["id"], ondelete="SET NULL"
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Remove user_id from newsletters first
    with op.batch_alter_table("newsletters", schema=None) as batch_op:
        batch_op.drop_constraint("fk_newsletters_user_id", type_="foreignkey")
        batch_op.drop_index(batch_op.f("ix_newsletters_user_id"))
        batch_op.drop_column("user_id")

    # Then drop users table
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_users_email"))

    op.drop_table("users")
    # ### end Alembic commands ###
