"""Remove articles JSON column from newsletters

Revision ID: 6a873169c45e
Revises: 9a6149c06069
Create Date: 2025-11-30 12:44:11.575242

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = "6a873169c45e"
down_revision: Union[str, Sequence[str], None] = "9a6149c06069"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("newsletters", "articles")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("newsletters", sa.Column("articles", sqlite.JSON(), nullable=False))
    # ### end Alembic commands ###
