"""Initial migration - create newsletters and source_stats tables

Revision ID: 877eb8ba9044
Revises:
Create Date: 2025-11-30 12:11:39.383513

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "877eb8ba9044"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "newsletters",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("summary", sa.Text(), nullable=True),
        sa.Column("language", sa.String(length=5), nullable=False),
        sa.Column("articles", sa.JSON(), nullable=False),
        sa.Column("audio_url", sa.String(length=500), nullable=True),
        sa.Column("confidence_score", sa.Float(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "source_stats",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("newsletter_id", sa.Integer(), nullable=False),
        sa.Column("category", sa.String(length=20), nullable=False),
        sa.Column("source_name", sa.String(length=100), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("article_count", sa.Integer(), nullable=False),
        sa.Column("confidence_score", sa.Float(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["newsletter_id"], ["newsletters.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_source_stats_category"), "source_stats", ["category"], unique=False)
    op.create_index(
        op.f("ix_source_stats_newsletter_id"), "source_stats", ["newsletter_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_source_stats_newsletter_id"), table_name="source_stats")
    op.drop_index(op.f("ix_source_stats_category"), table_name="source_stats")
    op.drop_table("source_stats")
    op.drop_table("newsletters")
    # ### end Alembic commands ###
