"""Add source_stats_daily table

Revision ID: acf26aaa2f75
Revises: b2088bf7a2d6
Create Date: 2026-01-06 12:06:43.970852

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "acf26aaa2f75"
down_revision: Union[str, Sequence[str], None] = "b2088bf7a2d6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "source_stats_daily",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("source_name", sa.String(length=100), nullable=False),
        sa.Column("category", sa.String(length=20), nullable=False),
        sa.Column("stat_date", sa.Date(), nullable=False),
        sa.Column("total_runs", sa.Integer(), nullable=False),
        sa.Column("total_articles", sa.Integer(), nullable=False),
        sa.Column("success_count", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("source_name", "category", "stat_date", name="uq_source_category_date"),
    )
    with op.batch_alter_table("source_stats_daily", schema=None) as batch_op:
        batch_op.create_index("ix_source_stats_daily_date", ["stat_date"], unique=False)

    with op.batch_alter_table("newsletters", schema=None) as batch_op:
        batch_op.alter_column(
            "language",
            existing_type=sa.VARCHAR(length=5),
            server_default=None,
            existing_nullable=False,
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("newsletters", schema=None) as batch_op:
        batch_op.alter_column(
            "language",
            existing_type=sa.VARCHAR(length=5),
            server_default=sa.text("'en'"),
            existing_nullable=False,
        )

    with op.batch_alter_table("source_stats_daily", schema=None) as batch_op:
        batch_op.drop_index("ix_source_stats_daily_date")

    op.drop_table("source_stats_daily")
    # ### end Alembic commands ###
